### ISSUE TITLE
Allow CSRF forms

### ISSUE THREAD

**Issue by brendean** [fusionjs/fusion-plugin-csrf-protection#110]
### Type of issue

Feature request

### Description

It would be nice for form submits to be able to leverage CSRF protection. This doesn't seem included in the library as is right now.

### Current behavior

Can only use CSRF for fetch calls

### Expected behavior

Ability to add `csrf-token` field to forms

**Comment by ganemone** [comment]
Chatted offline, we are planning on not supporting this at least in the near term
